version: '3'

services:

  www:
    container_name: apache
    build: .
    network_mode: bridge
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=mydb
      - MYSQL_ROOT_PASSWORD=root123
      - MYSQL_USER=root
